### ISSUE TITLE
Please update PyPI version

### ISSUE THREAD

**Issue by manicmaniac** [Tatsh/libipa#5]
Nice package but PyPI version is 0.0.5 which is out of date by 1.5 year, seems to contain some bugs.

**Comment by Tatsh** [comment]
Should be good now. [libipa 0.0.6](https://pypi.python.org/pypi/libipa/0.0.6) See [release notes](https://github.com/Tatsh/libipa/releases/tag/v0.0.6) (no I have not got a nice, exact way to convert to ReST for the PyPI page 😞 ).
